http:
  routers:
    captar-backend:
      entryPoints:
        - websecure
      rule: "Host(`captar.srv1842127.hstgr.cloud`) && PathPrefix(`/api`)"
      tls:
        certResolver: letsencrypt
      service: captar-backend
      priority: 100

    captar-frontend:
      entryPoints:
        - websecure
      rule: "Host(`captar.srv1842127.hstgr.cloud`)"
      tls:
        certResolver: letsencrypt
      service: captar-frontend

  services:
    captar-backend:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:8000"

    captar-frontend:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:3000"
